server:
  port: ${PORT:12003}

spring:
  application:
    name: tsuu-api
  flyway:
    enabled: true
    sql-migration-separator: '-'
    sql-migration-prefix: ''

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    net.sandrohc.tsuu: INFO