server:
  port: ${PORT:12020}

spring:
  application:
    name: tsuu-api
  data:
    mongodb:
      uri: mongodb://${DB_USER:tsuu}:${DB_PASS:tsuu}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:tsuu}?authSource=admin
  flyway:
    enabled: true
    sql-migration-separator: '-'
    sql-migration-prefix: ''

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    net.sandrohc.tsuu: INFO