server:
  port: ${PORT:12020}

spring:
  application:
    name: tsuu-api
  data:
    postgres:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:5432}
      database: ${DB_NAME:tsuu}
      username: ${DB_USER:tsuu}
      password: ${DB_PASS:tsuu}
  flyway:
    enabled: true
    sql-migration-separator: '-'
    sql-migration-prefix: ''

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

logging:
  level:
    net.sandrohc.tsuu: INFO